# Generated by Django 4.2.13 on 2026-04-25 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('offer_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('flat', 'Flat Amount Off'), ('combo', 'Combo Deal'), ('free_item', 'Buy X Get Y Free'), ('bogo', 'Buy One Get One')], max_length=20)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 30 for 30% off', max_digits=5, null=True)),
                ('discount_flat', models.DecimalField(blank=True, decimal_places=2, help_text='Flat amount off in ₹', max_digits=8, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('video', models.FileField(blank=True, help_text='MP4 video ad — plays muted+autoplay in hero carousel', null=True, upload_to='offers/videos/')),
                ('video_thumbnail', models.ImageField(blank=True, help_text='Poster frame shown before video loads', null=True, upload_to='offers/thumbnails/')),
                ('image', models.ImageField(blank=True, help_text='Static image — used if no video uploaded', null=True, upload_to='offers/images/')),
                ('emoji', models.CharField(default='🔥', max_length=8)),
                ('gradient_from', models.CharField(default='#1A0500', max_length=7)),
                ('gradient_to', models.CharField(default='#2D0A00', max_length=7)),
                ('accent_color', models.CharField(default='#E8521A', max_length=7)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, help_text='Leave blank for a lifetime / never-expiring offer', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('carousel_order', models.PositiveSmallIntegerField(default=0)),
                ('first_order_only', models.BooleanField(default=False, help_text='If True, only customers placing their FIRST order can redeem this offer')),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum cart subtotal required to apply this offer (₹)', max_digits=8, null=True)),
                ('max_redemptions_per_user', models.PositiveSmallIntegerField(default=0, help_text='0 = unlimited. Max times one customer can redeem this offer.')),
                ('coupon_code', models.CharField(blank=True, default='', help_text='Short code customers enter in cart to apply this offer', max_length=30)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('redemption_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_offers',
                'ordering': ['carousel_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'offer_items',
            },
        ),
        migrations.CreateModel(
            name='OfferRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('savings', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='offers.dailyoffer')),
            ],
            options={
                'db_table': 'offer_redemptions',
            },
        ),
    ]
