# Generated by Django 4.2.13 on 2026-04-25 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        ('orders', '0001_initial'),
        ('branches', '0001_initial'),
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerredemption',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='offeritem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='offeritem',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_items', to='offers.dailyoffer'),
        ),
        migrations.AddField(
            model_name='dailyoffer',
            name='applies_to',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to apply to all items in the combo', related_name='offers', to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='dailyoffer',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='dailyoffer',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Restrict this offer to one category only (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_offers', to='menu.menucategory'),
        ),
        migrations.AddIndex(
            model_name='dailyoffer',
            index=models.Index(fields=['branch', 'is_active'], name='daily_offer_branch__6ee1eb_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyoffer',
            index=models.Index(fields=['start_at', 'end_at'], name='daily_offer_start_a_717a49_idx'),
        ),
    ]
