# Generated by Django 4.2.13 on 2026-04-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyoffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
