# Generated by Django 4.2.13 on 2026-06-02 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0005_add_menuitemimage'),
        ('orders', '0003_order_payment_serial'),
        ('offers', '0005_dailyoffer_all_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReEngagementLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('coupon_sent', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'reengagement_logs',
            },
        ),
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('reward_sent_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'referral_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('signed_up', 'Referred user signed up'), ('ordered', 'Referred user placed qualifying order'), ('reward_sent', 'Referrer reward granted')], default='signed_up', max_length=15)),
                ('reward_coupon', models.CharField(blank=True, help_text='One-time coupon code sent to referrer as reward', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'referral_usages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dailyoffer',
            name='inactive_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Send to customers who have not ordered in this many days'),
        ),
        migrations.AddField(
            model_name='dailyoffer',
            name='reengagement_message',
            field=models.TextField(blank=True, help_text='Custom WhatsApp message. Use {name}, {discount}, {code} as placeholders.'),
        ),
        migrations.AddField(
            model_name='dailyoffer',
            name='referral_min_friend_order',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum order value the referred friend must place to trigger reward', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='dailyoffer',
            name='referral_reward_on_signup',
            field=models.BooleanField(default=False, help_text='Give reward immediately when friend signs up (not waiting for first order)'),
        ),
        migrations.AddField(
            model_name='dailyoffer',
            name='referral_reward_type',
            field=models.CharField(choices=[('coupon', 'Coupon Code Discount'), ('scratch', 'Scratch Card'), ('discount', 'Direct Cart Discount')], default='coupon', help_text='What the referrer earns when their friend qualifies', max_length=15),
        ),
        migrations.AddField(
            model_name='dailyoffer',
            name='referral_reward_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='₹ value or % of reward for referrer', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='dailyoffer',
            name='require_coupon',
            field=models.BooleanField(default=False, help_text='If True, coupon_code MUST be entered — offer cannot be auto-applied'),
        ),
        migrations.AddField(
            model_name='dailyoffer',
            name='welcome_bonus_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed ₹ bonus for new users (WELCOME type)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='dailyoffer',
            name='all_branches',
            field=models.BooleanField(default=False, help_text='Show to customers of ALL branches (SuperAdmin global offer)'),
        ),
        migrations.AlterField(
            model_name='dailyoffer',
            name='applies_to',
            field=models.ManyToManyField(blank=True, help_text='Restrict offer to these specific items (leave empty = all items)', related_name='offers', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='dailyoffer',
            name='auto_broadcast',
            field=models.BooleanField(default=False, help_text='Auto-broadcast to branch customers when this offer is activated'),
        ),
        migrations.AlterField(
            model_name='dailyoffer',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Restrict offer to this category only (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_offers', to='menu.menucategory'),
        ),
        migrations.AlterField(
            model_name='dailyoffer',
            name='coupon_code',
            field=models.CharField(blank=True, default='', help_text='Admin-set code customers enter in cart to claim this offer', max_length=30),
        ),
        migrations.AlterField(
            model_name='dailyoffer',
            name='discount_flat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Flat ₹ amount off', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='dailyoffer',
            name='first_order_only',
            field=models.BooleanField(default=False, help_text='Only customers placing their FIRST order can redeem this offer'),
        ),
        migrations.AlterField(
            model_name='dailyoffer',
            name='image',
            field=models.ImageField(blank=True, help_text='Offer poster — shown in cards and broadcast messages', null=True, upload_to='offers/images/'),
        ),
        migrations.AlterField(
            model_name='dailyoffer',
            name='max_redemptions_per_user',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = unlimited. Max times one customer can redeem.'),
        ),
        migrations.AlterField(
            model_name='dailyoffer',
            name='offer_type',
            field=models.CharField(choices=[('percentage', 'Percentage Discount'), ('flat', 'Flat Amount Off'), ('combo', 'Combo Deal'), ('free_item', 'Buy X Get Y Free'), ('bogo', 'Buy One Get One'), ('welcome', 'Welcome / First-Order Bonus'), ('referral', 'Share & Get Reward'), ('re_engagement', 'We Miss You (Re-engagement)'), ('scratch_card', 'Scratch Card (Reveal & Win)')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='dailyoffer',
            index=models.Index(fields=['offer_type', 'is_active'], name='daily_offer_offer_t_d85da1_idx'),
        ),
        migrations.AddField(
            model_name='referralusage',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='offers.referrallink'),
        ),
        migrations.AddField(
            model_name='referralusage',
            name='qualifying_order',
            field=models.ForeignKey(blank=True, help_text="The friend's first qualifying order", null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddField(
            model_name='referralusage',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referrallink',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to='offers.dailyoffer'),
        ),
        migrations.AddField(
            model_name='referrallink',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reengagementlog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reengagementlog',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reengagement_logs', to='offers.dailyoffer'),
        ),
        migrations.AlterUniqueTogether(
            name='referralusage',
            unique_together={('link', 'referred_user')},
        ),
        migrations.AlterUniqueTogether(
            name='referrallink',
            unique_together={('offer', 'referrer')},
        ),
        migrations.AlterUniqueTogether(
            name='reengagementlog',
            unique_together={('offer', 'customer')},
        ),
    ]
