# Generated by Django 4.2.13 on 2026-06-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0015_remove_branchtable_unique_branch_table_number_and_more'),
        ('offers', '0006_add_scratch_card_offer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyoffer',
            name='selected_branches',
            field=models.ManyToManyField(blank=True, help_text='Apply to these specific branches (leave empty = FK branch only)', related_name='selected_offers', to='branches.branch'),
        ),
    ]
