# Generated by Django 4.2.13 on 2026-04-27 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='Staff/BranchAdmin who marked this order completed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_completed_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
