# Generated by Django 4.2.13 on 2026-04-27 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_order_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_marked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_serial',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
