# Generated by Django 4.2.13 on 2026-04-25 07:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCustomisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_default', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'item_customisations',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Banner image shown at the top of the category page', null=True, upload_to='categories/')),
                ('emoji', models.CharField(default='🍽️', max_length=8)),
                ('gradient_from', models.CharField(default='#1A0800', max_length=7)),
                ('gradient_to', models.CharField(default='#2D1200', max_length=7)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='branches.branch')),
            ],
            options={
                'db_table': 'menu_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, help_text='Primary product photo', null=True, upload_to='menu_items/')),
                ('image_thumb', models.ImageField(blank=True, help_text='Auto-generated thumbnail (128×128)', null=True, upload_to='menu_items/thumbs/')),
                ('emoji', models.CharField(default='🍽️', max_length=8)),
                ('dietary_type', models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('vegan', 'Vegan')], default='non_veg', max_length=10)),
                ('spice_level', models.CharField(choices=[('none', 'Not Applicable'), ('mild', 'Mild'), ('medium', 'Medium'), ('hot', 'Hot'), ('extra', 'Extra Hot')], default='medium', max_length=10)),
                ('calories', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('low_stock_threshold', models.PositiveSmallIntegerField(default=10)),
                ('carries_over', models.BooleanField(default=True, help_text='If True, remaining stock rolls over to the next day at midnight.')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('discount', models.PositiveSmallIntegerField(blank=True, help_text='Discount percentage, e.g. 20 = 20% off. Leave blank for no discount.', null=True)),
                ('measurement_unit', models.CharField(choices=[('pcs', 'Pieces'), ('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Millilitres'), ('l', 'Litres'), ('portion', 'Portion'), ('box', 'Box'), ('cup', 'Cup')], default='pcs', help_text='Unit used to describe quantity: pcs, g, kg, ml, l, portion, box, cup', max_length=10)),
                ('unit_quantity', models.PositiveSmallIntegerField(blank=True, help_text='e.g. 500 (for 500g), 6 (for 6 pcs), 1 (for 1kg)', null=True)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('prep_time_min', models.PositiveSmallIntegerField(default=8)),
                ('prep_time_max', models.PositiveSmallIntegerField(default=15)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='branches.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menucategory')),
            ],
            options={
                'db_table': 'menu_items',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ItemReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('admin_reply', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='menu.menuitem')),
            ],
            options={
                'db_table': 'item_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
