# Generated by Django 4.2.13 on 2026-04-25 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreview',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='orders.order'),
        ),
        migrations.AddField(
            model_name='itemcustomisation',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customisations', to='menu.menuitem'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['branch', 'category'], name='menu_items_branch__176cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['branch', 'is_available'], name='menu_items_branch__a60f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_featured'], name='menu_items_is_feat_1963a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('branch', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='menucategory',
            unique_together={('branch', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='itemreview',
            unique_together={('menu_item', 'customer', 'order')},
        ),
    ]
