# Generated by Django 4.2.13 on 2026-04-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_chicken',
            field=models.BooleanField(default=False, help_text='Appears in Chicken Items section on home page'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_cold_drinks',
            field=models.BooleanField(default=False, help_text='Appears in Cold Drinks section on home page'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_hotdeals',
            field=models.BooleanField(default=False, help_text='Appears in Hot Deals section on home page'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_snacks',
            field=models.BooleanField(default=False, help_text='Appears in Snacks & Munchies section on home page'),
        ),
    ]
