# Generated by Django 4.2.13 on 2026-05-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_add_home_section_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='all_branches',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='all_branches',
            field=models.BooleanField(default=False),
        ),
    ]
