# Generated by Django 4.2.13 on 2026-06-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_add_buckets_combo_flags'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['all_branches'], name='menu_items_all_bra_12c3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['branch', 'is_hotdeals'], name='menu_items_branch__8f90b5_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['branch', 'is_buckets'], name='menu_items_branch__50fd8c_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['branch', 'is_combo'], name='menu_items_branch__3122eb_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['branch', 'is_chicken'], name='menu_items_branch__dae3de_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['branch', 'is_snacks'], name='menu_items_branch__13e31c_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['branch', 'is_cold_drinks'], name='menu_items_branch__626c45_idx'),
        ),
    ]
