# Generated by Django 4.2.13 on 2026-04-25 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('menu', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('yesterday_remaining', models.IntegerField(default=0)),
                ('new_stock_added', models.IntegerField(default=0)),
                ('today_stock', models.IntegerField(default=0)),
                ('used_stock', models.IntegerField(default=0)),
                ('remaining_stock', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='branches.branch')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='menu.menuitem')),
            ],
            options={
                'db_table': 'stock_records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('opening_set', 'Opening Stock Set'), ('top_up', 'Mid-Day Top-Up'), ('auto_deduction', 'Order Deduction'), ('manual_correction', 'Manual Correction'), ('carryover', 'Nightly Carryover'), ('waste', 'Waste / Damage')], max_length=25)),
                ('qty_before', models.IntegerField()),
                ('qty_changed', models.IntegerField()),
                ('qty_after', models.IntegerField()),
                ('role_at_time', models.CharField(blank=True, max_length=20)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='branches.branch')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_changes', to=settings.AUTH_USER_MODEL)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='menu.menuitem')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('stock_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='stock.stockrecord')),
            ],
            options={
                'db_table': 'stock_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('low', 'Low Stock'), ('out', 'Out of Stock')], max_length=10)),
                ('remaining', models.IntegerField()),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem')),
            ],
            options={
                'db_table': 'stock_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stockrecord',
            index=models.Index(fields=['branch', 'date'], name='stock_recor_branch__da8450_idx'),
        ),
        migrations.AddIndex(
            model_name='stockrecord',
            index=models.Index(fields=['menu_item', 'date'], name='stock_recor_menu_it_8a23eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockrecord',
            unique_together={('branch', 'menu_item', 'date')},
        ),
        migrations.AddIndex(
            model_name='stocklog',
            index=models.Index(fields=['branch', 'timestamp'], name='stock_logs_branch__61b98d_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklog',
            index=models.Index(fields=['menu_item', 'timestamp'], name='stock_logs_menu_it_8b3a53_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklog',
            index=models.Index(fields=['changed_by'], name='stock_logs_changed_5a0bf6_idx'),
        ),
    ]
