# Generated by Django 4.2.13 on 2026-06-02 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0009_drop_orphaned_ad_banner_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklog',
            name='change_type',
            field=models.CharField(choices=[('opening_set', 'Opening Stock Set'), ('top_up', 'Mid-Day Top-Up'), ('auto_deduction', 'Order Deduction'), ('manual_correction', 'Manual Correction'), ('carryover', 'Nightly Carryover'), ('rollback', 'Manual Rollback from Yesterday'), ('waste', 'Waste / Damage'), ('lock', 'Stock Locked for Day')], max_length=25),
        ),
        migrations.CreateModel(
            name='StockDailyLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('is_system', models.BooleanField(default=False)),
                ('total_added', models.IntegerField(default=0)),
                ('total_used', models.IntegerField(default=0)),
                ('total_remaining', models.IntegerField(default=0)),
                ('rollback_count', models.IntegerField(default=0)),
                ('items_count', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_locks', to='branches.branch')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_locks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_daily_locks',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['branch', 'date'], name='stock_daily_branch__b28123_idx')],
                'unique_together': {('branch', 'date')},
            },
        ),
    ]
