# Generated by Django 4.2.13 on 2026-04-25 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('max_tables', models.PositiveSmallIntegerField(default=20, help_text='Maximum number of dine-in tables. Customers see this when selecting a table.')),
                ('operating_hours', models.JSONField(blank=True, default=dict)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'db_table': 'branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_enabled', models.BooleanField(default=True, help_text='Master switch — if False, no points are earned or redeemed')),
                ('loyalty_earn_rate', models.DecimalField(decimal_places=2, default=1.0, help_text='Points earned per ₹1 spent. e.g. 1.0 = 1 pt per ₹1', max_digits=6)),
                ('loyalty_redeem_rate', models.DecimalField(decimal_places=2, default=0.1, help_text='₹ value of 1 loyalty point. e.g. 0.10 = 100 pts = ₹10', max_digits=6)),
                ('loyalty_min_redeem', models.PositiveIntegerField(default=100, help_text='Minimum points required to redeem in one transaction')),
                ('loyalty_redeem_step', models.PositiveIntegerField(default=100, help_text='Points must be redeemed in multiples of this number')),
                ('loyalty_max_redeem_pct', models.PositiveSmallIntegerField(default=50, help_text='Maximum % of order total that can be paid with loyalty points')),
                ('spin_enabled', models.BooleanField(default=True)),
                ('spin_max_uses', models.PositiveSmallIntegerField(default=1, help_text='Max times a single customer can spin per day (0 = unlimited)')),
                ('spin_prizes', models.JSONField(blank=True, default=list, help_text='JSON array of prize objects: [{label, color, prob, discount_pct}]')),
                ('scratch_enabled', models.BooleanField(default=True)),
                ('scratch_discount_pct', models.PositiveSmallIntegerField(default=15, help_text='Discount % revealed by the scratch card')),
                ('scratch_max_uses', models.PositiveSmallIntegerField(default=1, help_text='Max times a customer can use scratch card per day')),
                ('scratch_coupon_code', models.CharField(default='SCRATCH15', help_text='Coupon code revealed by scratch card', max_length=20)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'db_table': 'site_config',
            },
        ),
    ]
