# Generated by Django 4.2.13 on 2026-04-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='enable_dine_in',
            field=models.BooleanField(default=True, help_text='Allow dine-in orders at this branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='enable_pickup',
            field=models.BooleanField(default=True, help_text='Allow pickup orders at this branch'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='max_tables',
            field=models.PositiveSmallIntegerField(default=20, help_text='Maximum number of dine-in tables.'),
        ),
    ]
