# Generated by Django 4.2.13 on 2026-05-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_enable_dine_in_branch_enable_pickup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='login_image',
            field=models.ImageField(blank=True, help_text='Background image shown on the customer login page', null=True, upload_to='site/login/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='login_video_url',
            field=models.CharField(blank=True, default='', help_text='URL of video to play on the login page desktop hero (leave blank to use default)', max_length=500),
        ),
    ]
