# Generated by Django 4.2.13 on 2026-05-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_add_login_image_to_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='pickup_upi_only',
            field=models.BooleanField(default=False, help_text='If true, pickup orders must pay via UPI only'),
        ),
    ]
