# Generated by Django 4.2.13 on 2026-05-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0007_branch_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='home_ads',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of home page banner ads. Each: {"id","title","image_url","link","active"}'),
        ),
        migrations.AlterField(
            model_name='spinlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
