# Generated by Django 4.2.13 on 2026-06-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0009_drop_orphaned_ad_banner_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='gpay_upi_id',
            field=models.CharField(blank=True, help_text='Google Pay UPI ID', max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='phonepe_upi_id',
            field=models.CharField(blank=True, help_text='PhonePe UPI ID', max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='supermoney_upi_id',
            field=models.CharField(blank=True, help_text='SuperMoney UPI ID (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='upi_id',
            field=models.CharField(blank=True, help_text='General UPI ID for payment QR (e.g. knfc.branch1@upi)', max_length=100),
        ),
    ]
