# Generated by Django 4.2.13 on 2026-06-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0010_add_upi_ids_to_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='about_content',
            field=models.TextField(blank=True, default='', help_text='Rich text / paragraphs for the About page body'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_headline',
            field=models.CharField(blank=True, default='About KNFC Fried Chicken', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/about/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_stats',
            field=models.JSONField(blank=True, default=list, help_text='[{"label":"Branches","value":"3"},{"label":"Happy Customers","value":"10000+"}]'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_tagline',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='about_video_url',
            field=models.CharField(blank=True, default='', help_text='YouTube / direct MP4 URL for About page hero video', max_length=500),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='blog_posts',
            field=models.JSONField(blank=True, default=list, help_text='[{"id","title","slug","excerpt","content","image_url","author","date","tags":[]}]'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='careers_intro',
            field=models.TextField(blank=True, default='', help_text='Intro text for the Careers page'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='careers_openings',
            field=models.JSONField(blank=True, default=list, help_text='[{"title","department","location","type":"Full-time","description","apply_email"}]'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contact_address',
            field=models.TextField(blank=True, default='', help_text='Physical address shown on Contact and About pages'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Support email address', max_length=254),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contact_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number shown on Contact page and footer', max_length=25),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='contact_wa_number',
            field=models.CharField(blank=True, default='', help_text='WhatsApp number for chat support (digits only, e.g. 919876543210)', max_length=25),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_map_query',
            field=models.CharField(blank=True, default='KNFC+Fried+Chicken', help_text='Google Maps search query for the footer embed', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_show_map',
            field=models.BooleanField(default=True, help_text='Show Google Map in desktop footer'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='reengagement_default_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Default inactive_days used when creating re-engagement offers'),
        ),
    ]
