# Generated by Django 4.2.13 on 2026-06-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0011_siteconfig_contact_about_blog_careers'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='home_section_images',
            field=models.JSONField(blank=True, default=dict, help_text='Images shown as banners for themed home-page sections. Keys: "is_hotdeals", "is_chicken", "is_snacks", "is_cold_drinks". Each value: {"image_url": "...", "tagline": "..."}'),
        ),
    ]
