# Generated by Django 4.2.13 on 2026-06-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0014_add_branch_table'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='branchtable',
            name='unique_branch_table_number',
        ),
        migrations.AlterField(
            model_name='branchtable',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=4, help_text='How many people this table seats'),
        ),
        migrations.AlterField(
            model_name='branchtable',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Hidden from customers if False'),
        ),
        migrations.AlterField(
            model_name='branchtable',
            name='label',
            field=models.CharField(help_text="Display name shown to customer, e.g. 'Window Table A'", max_length=60),
        ),
        migrations.AlterField(
            model_name='branchtable',
            name='table_number',
            field=models.PositiveSmallIntegerField(help_text='Internal number used in orders (e.g. 1, 2, 3)'),
        ),
        migrations.AlterUniqueTogether(
            name='branchtable',
            unique_together={('branch', 'table_number')},
        ),
    ]
